-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Task CASCADE; -- Muista IF EXISTS ja CASCADE parametrit!
DROP TABLE IF EXISTS Person CASCADE;
DROP TABLE IF EXISTS Priority CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS Task_status CASCADE;
DROP TABLE IF EXISTS Task_category CASCADE;

