-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS person CASCADE; -- Muista IF EXISTS ja CASCADE parametrit!
DROP TABLE IF EXISTS task_priority CASCADE;
DROP TABLE IF EXISTS task_status CASCADE;
DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS task_category CASCADE;
